import { ACCESS_SCOPE } from "./accessScope.js";
import {
  PERMISSIONS,
  PERMISSION_GROUPS,
  ALL_PERMISSIONS,
} from "../utils/permission.js";

const {
  ORGANIZATION,
  USERS,
  ROLES,
  LEADS,
  CONTACTS,
  ACCOUNTS,
  DEALS,
  TASKS,
  NOTES,
  MEETINGS,
  PIPELINES,
  REPORTS,
  NOTIFICATIONS,
  ACTIVITY,
  AI,
} = PERMISSION_GROUPS;

export const SYSTEM_ROLE_NAMES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  SALES_REP: "SALES_REP",
};

export const DEFAULT_ROLE_DEFINITIONS = {
  [SYSTEM_ROLE_NAMES.OWNER]: {
    description: "Full access to the organization and all CRM resources",
    permissions: [...ALL_PERMISSIONS],
    accessScope: {
      lead: ACCESS_SCOPE.ALL,
      contact: ACCESS_SCOPE.ALL,
      account: ACCESS_SCOPE.ALL,
      deal: ACCESS_SCOPE.ALL,
      task: ACCESS_SCOPE.ALL,
      note: ACCESS_SCOPE.ALL,
      meeting: ACCESS_SCOPE.ALL,
      user: ACCESS_SCOPE.ALL,
      report: ACCESS_SCOPE.ALL,
    },
  },

  [SYSTEM_ROLE_NAMES.ADMIN]: {
    description: "Administrative access to users, CRM modules, and reporting",
    permissions: [
      ...ORGANIZATION.filter((key) => key !== PERMISSIONS.ORG_BILLING_UPDATE),
      ...USERS,
      ...ROLES,
      ...LEADS,
      ...CONTACTS,
      ...ACCOUNTS,
      ...DEALS,
      ...TASKS,
      ...NOTES,
      ...MEETINGS,
      ...PIPELINES,
      ...REPORTS,
      ...NOTIFICATIONS,
      ...ACTIVITY,
      ...AI,
    ],
    accessScope: {
      lead: ACCESS_SCOPE.ALL,
      contact: ACCESS_SCOPE.ALL,
      account: ACCESS_SCOPE.ALL,
      deal: ACCESS_SCOPE.ALL,
      task: ACCESS_SCOPE.ALL,
      note: ACCESS_SCOPE.ALL,
      meeting: ACCESS_SCOPE.ALL,
      user: ACCESS_SCOPE.ALL,
      report: ACCESS_SCOPE.ALL,
    },
  },

  [SYSTEM_ROLE_NAMES.MANAGER]: {
    description:
      "Team manager with team-wide visibility and assignment abilities",
    permissions: [
      PERMISSIONS.ORG_READ,

      PERMISSIONS.USER_READ,

      PERMISSIONS.ROLE_READ,
      PERMISSIONS.PERMISSION_READ,

      PERMISSIONS.LEAD_CREATE,
      PERMISSIONS.LEAD_READ,
      PERMISSIONS.LEAD_UPDATE,
      PERMISSIONS.LEAD_ASSIGN,
      PERMISSIONS.LEAD_IMPORT,
      PERMISSIONS.LEAD_EXPORT,
      PERMISSIONS.LEAD_CONVERT,

      PERMISSIONS.CONTACT_CREATE,
      PERMISSIONS.CONTACT_READ,
      PERMISSIONS.CONTACT_UPDATE,
      PERMISSIONS.CONTACT_IMPORT,
      PERMISSIONS.CONTACT_EXPORT,

      PERMISSIONS.ACCOUNT_CREATE,
      PERMISSIONS.ACCOUNT_READ,
      PERMISSIONS.ACCOUNT_UPDATE,

      PERMISSIONS.DEAL_CREATE,
      PERMISSIONS.DEAL_READ,
      PERMISSIONS.DEAL_UPDATE,
      PERMISSIONS.DEAL_ASSIGN,
      PERMISSIONS.DEAL_MOVE_STAGE,
      PERMISSIONS.DEAL_EXPORT,

      PERMISSIONS.TASK_CREATE,
      PERMISSIONS.TASK_READ,
      PERMISSIONS.TASK_UPDATE,
      PERMISSIONS.TASK_ASSIGN,
      PERMISSIONS.TASK_COMPLETE,

      PERMISSIONS.NOTE_CREATE,
      PERMISSIONS.NOTE_READ,
      PERMISSIONS.NOTE_UPDATE,

      PERMISSIONS.MEETING_CREATE,
      PERMISSIONS.MEETING_READ,
      PERMISSIONS.MEETING_UPDATE,

      PERMISSIONS.PIPELINE_READ,

      PERMISSIONS.REPORT_READ,
      PERMISSIONS.DASHBOARD_READ,

      PERMISSIONS.NOTIFICATION_READ,
      PERMISSIONS.NOTIFICATION_UPDATE,

      PERMISSIONS.ACTIVITY_READ,

      PERMISSIONS.AI_EMAIL_GENERATE,
      PERMISSIONS.AI_LEAD_SCORE,
      PERMISSIONS.AI_MEETING_SUMMARY,
    ],
    accessScope: {
      lead: ACCESS_SCOPE.TEAM,
      contact: ACCESS_SCOPE.TEAM,
      account: ACCESS_SCOPE.TEAM,
      deal: ACCESS_SCOPE.TEAM,
      task: ACCESS_SCOPE.TEAM,
      note: ACCESS_SCOPE.TEAM,
      meeting: ACCESS_SCOPE.TEAM,
      user: ACCESS_SCOPE.TEAM,
      report: ACCESS_SCOPE.TEAM,
    },
  },

  [SYSTEM_ROLE_NAMES.SALES_REP]: {
    description:
      "Sales representative with day-to-day CRM access for owned records",
    permissions: [
      PERMISSIONS.LEAD_CREATE,
      PERMISSIONS.LEAD_READ,
      PERMISSIONS.LEAD_UPDATE,

      PERMISSIONS.CONTACT_CREATE,
      PERMISSIONS.CONTACT_READ,
      PERMISSIONS.CONTACT_UPDATE,

      PERMISSIONS.ACCOUNT_CREATE,
      PERMISSIONS.ACCOUNT_READ,
      PERMISSIONS.ACCOUNT_UPDATE,

      PERMISSIONS.DEAL_CREATE,
      PERMISSIONS.DEAL_READ,
      PERMISSIONS.DEAL_UPDATE,
      PERMISSIONS.DEAL_MOVE_STAGE,

      PERMISSIONS.TASK_CREATE,
      PERMISSIONS.TASK_READ,
      PERMISSIONS.TASK_UPDATE,
      PERMISSIONS.TASK_COMPLETE,

      PERMISSIONS.NOTE_CREATE,
      PERMISSIONS.NOTE_READ,
      PERMISSIONS.NOTE_UPDATE,

      PERMISSIONS.MEETING_CREATE,
      PERMISSIONS.MEETING_READ,
      PERMISSIONS.MEETING_UPDATE,

      PERMISSIONS.PIPELINE_READ,

      PERMISSIONS.DASHBOARD_READ,

      PERMISSIONS.NOTIFICATION_READ,
      PERMISSIONS.NOTIFICATION_UPDATE,

      PERMISSIONS.ACTIVITY_READ,

      PERMISSIONS.AI_EMAIL_GENERATE,
      PERMISSIONS.AI_MEETING_SUMMARY,
    ],
    accessScope: {
      lead: ACCESS_SCOPE.OWN,
      contact: ACCESS_SCOPE.OWN,
      account: ACCESS_SCOPE.OWN,
      deal: ACCESS_SCOPE.OWN,
      task: ACCESS_SCOPE.OWN,
      note: ACCESS_SCOPE.OWN,
      meeting: ACCESS_SCOPE.OWN,
      user: ACCESS_SCOPE.OWN,
      report: ACCESS_SCOPE.OWN,
    },
  },
};
